### PR TITLE
Remaining endpoints v1.1.0

### PR DESCRIPTION
**Pull request by ShamsUlAzeem**
I'll be adding the remaining swagger endpoints in the pull request

### CODE REVIEW

**Comment by crockpotveggies** [comment]
@ShamsUlAzeem can you please do a quick rundown by testing with this script here? Once that is complete I will merge: https://gist.github.com/crockpotveggies/ab4f850a8ac1e1b1271e4a7ab20b82bc

You may have to modify the script to use a different model

**Comment by ShamsUlAzeem** [comment]
@crockpotveggies sure I'll do that.

Also, I'll be using that testing script for each endpoint and write a folder like [this](https://github.com/SkymindIO/skil-clients/tree/master/python/test). I think this is much more manageable for later testings as well.

**Comment by ShamsUlAzeem** [comment]
I'll write the tests this week

**Comment by ShamsUlAzeem** [comment]
@crockpotveggies I'll be using this file for testing https://github.com/SkymindIO/skil-clients/blob/remaining_endpoints_v1.1.0_tests/python/test/test_default_api.py

**Comment by ShamsUlAzeem** [comment]
@crockpotveggies writing tests here: https://github.com/SkymindIO/skil-clients/pull/4

**Comment by crockpotveggies** [comment]
Overruled by #4

**Pull request closed without merging**
